digital_forensics_5:
  title: "Challenge 5: Digital Forensics"
  summary: "Examine data and uncover clues in this forensic challenge."
  description: "Phasellus accumsan velit nec justo vehicula, a sagittis tortor vehicula. Vivamus commodo, lorem nec auctor posuere."
  flag: "5"