web_exploit_3:
  title: "Challenge 3: Web Exploitation"
  summary: "Find vulnerabilities in the web application to retrieve hidden data."
  description: "Nullam dictum massa vel nulla vehicula, non consequat nisl efficitur. Donec ut dolor ac nisi euismod aliquam."
  completed: false
  flag: "3"