- name: Install the latest version of MariaDB
  ansible.builtin.package:
    name:
      - mariadb
    state: latest
  become: true

- name: Start MariaDB
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: yes
  become: true