- name: Install the latest version of MariaDB
  ansible.builtin.package:
    name:
      - mariadb-server
    state: latest
  become: true

- name: Copy mariadb config file
  src: ../files/mariadb_config
  dest: /etc/my.cnf.d/mariadb-server.cnf

- name: Start MariaDB
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: yes
  become: true