- name: Update apt cache
  apt:
    update_cache: yes


- name: Install Python and pip
  apt:
    name: ['python3', 'python3-pip']
    state: present

- name: Install Flask
  pip:
    name: flask
    state: latest

#- name: Copy Flask app to server
#  copy:
#    src: /path/to/your/flask/app.py
#    dest: /path/to/destination/app.py

# No changes needed for installing Python, pip, and Flask
- name: Run Flask app
  command: python3 ../flask/hello.py
  environment:
    FLASK_ENV: development
  async: 3600
  poll: 0
  when: flask_proxy_enabled != true  # Skip this if Caddy is acting as a reverse proxy
