- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Python and pip
  apt:
    name: ['python3', 'python3-pip']
    state: present

- name: Copy the Bermuda service file
  copy:
    src: files/bermuda.service
    dest: /etc/systemd/system/bermuda.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd daemon
  command: systemctl daemon-reload

- name: Enable the Bermuda service
  systemd:
    name: bermuda.service
    enabled: yes

- name: Start the Bermuda service
  systemd:
    name: bermuda.service
    state: started