- name: Open HTTP and HTTPS ports on firewall
  ansible.builtin.firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - "80/tcp"
    - "443/tcp"

- name: Always reload firewalld
  ansible.builtin.service:
    name: firewalld
    state: reloaded

- name: Install Python and pip
  package:
    name: ["python3", "python3-pip", "python3-devel"]
    state: present

- name: Clone the repository
  git:
    repo: "/opt/sourcecode"
    dest: "/home/podman/Project-Bermuda"
    version: main # Or specify a branch or tag if needed
    force: yes # Ensures the repository is cloned even if the directory exists
    update: yes # Pulls changes if the repository already exists
  become_user: podman

- name: copy credentials file
  copy:
    src: ../../flask/config/credentials.json.enc
    dest: /home/podman/Project-Bermuda/flask/config/credentials.json
    owner: podman
    group: podman

- name: copy config file
  copy:
    src: ../files/prod_config.json
    dest: /home/podman/Project-Bermuda/flask/config/config.json
    owner: podman
    group: podman

- name: Create the virtual environment
  command:
    cmd: python3 -m venv /home/podman/Project-Bermuda/flask/venv
    creates: "/home/podman/Project-Bermuda/flask/venv/bin/activate"
  become_user: podman

- name: Install dependencies frombe requirements.txt
  command: "/home/podman/Project-Bermuda/flask/venv/bin/pip install -r /home/podman/Project-Bermuda/flask/requirements.txt"
  become_user: podman

- name: Copy the Bermuda service file
  copy:
    src: files/bermuda.service
    dest: /etc/systemd/system/bermuda.service
    owner: root
    group: root
    mode: "0644"

- name: Reload systemd daemon
  command: systemctl daemon-reload

- name: Enable the Bermuda service
  systemd:
    name: bermuda.service
    enabled: yes

- name: Start the Bermuda service
  systemd:
    name: bermuda.service
    state: restarted
