- name: Install the latest version of MariaDB
  ansible.builtin.package:
    name:
      - mariadb-server
    state: latest
  become: true

- name: Copy MariaDB config file
  ansible.builtin.copy:
    src: ../files/mariadb_config
    dest: /etc/my.cnf.d/mariadb-server.cnf
    owner: root
    group: root
    mode: '0644'
  register: config_file_changed

- name: Restart MariaDB if the config file changed
  ansible.builtin.service:
    name: mariadb
    state: restarted
  become: true
  when: config_file_changed is defined and config_file_changed.changed

- name: Ensure MariaDB is running
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: yes
  become: true

- name: Ensure MariaDB user is present with the correct password
  community.mysql.mysql_user:
    name: "bermuda"
    password: "bermuda_test"
    host: "%"
    priv: "*.*:ALL"
    state: present
  become: true
