- name: Deploy Flask Application
  hosts: localhost
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Python and pip
      apt:
        name: ['python3', 'python3-pip']
        state: present

    - name: Install virtualenv
      pip:
        name: virtualenv
        state: present

    - name: Create virtual environment
      command: python3 -m venv /path/to/venv

    - name: Activate virtual environment
      command: source /path/to/venv/bin/activate

    - name: Install Flask
      pip:
        name: flask
        state: present

    - name: Copy Flask app to server
      copy:
        src: /path/to/your/flask/app.py
        dest: /path/to/destination/app.py

    - name: Run Flask app
      command: python /path/to/destination/app.py

#- name: Install Flask
#  ansible.builtin.pip:
#    name: Flask
#    state: present
#  become: yes