- name: Install Python and pip
  package:
    name: ['python3', 'python3-pip']
    state: present
- name: Create the virtual environment
  command: python3 -m venv /home/podman/Project-Bermuda/flask/venv
  creates: "/home/podman/Project-Bermuda/flask/venv{{ venv_path }}/bin/activate"

- name: Install dependencies from requirements.txt
  command: /home/podman/Project-Bermuda/flask/venv/bin/pip install -r requirements.txt"
  when: requirements_file is file

- name: Copy the Bermuda service file
  copy:
    src: files/bermuda.service
    dest: /etc/systemd/system/bermuda.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd daemon
  command: systemctl daemon-reload

- name: Enable the Bermuda service
  systemd:
    name: bermuda.service
    enabled: yes

- name: Start the Bermuda service
  systemd:
    name: bermuda.service
    state: started