- hosts: localhost
  tasks:
    #Comment in this block for localhost testing
    - name: Configure Users
      ansible.builtin.include_tasks:
        file: tasks/configure_users.yml

    - name: Configure MariaDB
      ansible.builtin.include_tasks:
        file: tasks/configure_mariadb.yml

    - name: Configure Flask
      ansible.builtin.include_tasks:
        file: tasks/configure_flask.yml

    - name: Configure Caddy
      ansible.builtin.include_tasks:
        file: tasks/configure_caddy.yml
